import type { PortfolioData } from '@/types/portfolio'

export const mockData: PortfolioData = {
  projects: [
    {
      id: '1',
      title: 'E-Commerce Platform',
      description: 'A full-stack e-commerce solution with real-time inventory management, payment processing, and admin dashboard built for scale.',
      image: '/projects/ecommerce.png',
      tags: ['Next.js', 'React', 'TypeScript', 'Stripe', 'PostgreSQL'],
      url: 'https://github.com',
      featured: true,
      size: 'large',
    },
    {
      id: '2',
      title: 'AI Chat Assistant',
      description: 'Machine learning-powered conversational AI with context awareness, multi-language support, and real-time response streaming.',
      image: '/projects/ai-chat.png',
      tags: ['Python', 'TensorFlow', 'React', 'WebSocket'],
      url: 'https://github.com',
      featured: true,
      size: 'large',
    },
    {
      id: '3',
      title: 'Design System',
      description: 'Enterprise-grade component library with Storybook, accessibility compliance, and automated visual regression testing.',
      image: '/projects/design-system.png',
      tags: ['React', 'TypeScript', 'Tailwind', 'Storybook'],
      url: 'https://github.com',
      featured: true,
      size: 'large',
    },
  ],
  archivedProjects: [
    {
      id: '4',
      title: 'Real-time Analytics',
      description: 'Live data visualization dashboard with WebSocket integration and custom metrics.',
      image: '/projects/analytics.png',
      tags: ['React', 'D3.js', 'Node.js', 'WebSocket'],
      url: 'https://github.com',
      featured: false,
      size: 'small',
    },
    {
      id: '5',
      title: 'Mobile App',
      description: 'Cross-platform mobile application for task management with offline capabilities.',
      image: '/projects/mobile.png',
      tags: ['React Native', 'Firebase', 'Expo'],
      url: 'https://github.com',
      featured: false,
      size: 'small',
    },
    {
      id: '6',
      title: 'Cloud Infrastructure',
      description: 'Terraform-based infrastructure as code for scalable cloud deployments.',
      image: '/projects/infrastructure.png',
      tags: ['Terraform', 'AWS', 'Docker', 'Kubernetes'],
      url: 'https://github.com',
      featured: false,
      size: 'small',
    },
  ],
  experience: [
    {
      id: '1',
      role: 'Senior Full-Stack Engineer',
      company: 'Tech Innovations Inc',
      dateStart: '2021',
      dateEnd: 'Present',
      description: [
        'Led development of microservices architecture serving 1M+ daily users',
        'Implemented automated testing pipeline reducing deployment failures by 80%',
        'Mentored 5+ junior developers and established coding standards',
        'Optimized database queries improving application performance by 40%',
      ],
      skills: ['Next.js', 'Node.js', 'PostgreSQL', 'AWS', 'Docker'],
    },
    {
      id: '2',
      role: 'Full-Stack Developer',
      company: 'Digital Solutions Co',
      dateStart: '2019',
      dateEnd: '2021',
      description: [
        'Built responsive web applications using React and Vue.js',
        'Developed RESTful APIs and implemented real-time features with WebSockets',
        'Collaborated with design team to implement pixel-perfect UIs',
        'Maintained legacy systems while gradually migrating to modern tech stack',
      ],
      skills: ['React', 'Vue.js', 'Express', 'MongoDB', 'AWS'],
    },
    {
      id: '3',
      role: 'Junior Developer',
      company: 'StartUp Labs',
      dateStart: '2018',
      dateEnd: '2019',
      description: [
        'Developed frontend features for mobile-first web applications',
        'Fixed bugs and improved code quality across the codebase',
        'Participated in agile ceremonies and sprint planning',
        'Learned modern web development practices and tools',
      ],
      skills: ['JavaScript', 'React', 'CSS', 'Git', 'Jest'],
    },
  ],
  skills: [
    { id: '1', name: 'React', category: 'Frontend' },
    { id: '2', name: 'Next.js', category: 'Frontend' },
    { id: '3', name: 'TypeScript', category: 'Frontend' },
    { id: '4', name: 'Tailwind CSS', category: 'Frontend' },
    { id: '5', name: 'Vue.js', category: 'Frontend' },
    { id: '6', name: 'Node.js', category: 'Backend' },
    { id: '7', name: 'Express', category: 'Backend' },
    { id: '8', name: 'PostgreSQL', category: 'Backend' },
    { id: '9', name: 'MongoDB', category: 'Backend' },
    { id: '10', name: 'Python', category: 'Backend' },
    { id: '11', name: 'Docker', category: 'Tools' },
    { id: '12', name: 'Kubernetes', category: 'Tools' },
    { id: '13', name: 'AWS', category: 'Tools' },
    { id: '14', name: 'Git', category: 'Tools' },
    { id: '15', name: 'Figma', category: 'Design' },
    { id: '16', name: 'UI/UX Design', category: 'Design' },
  ],
}
